### ISSUE TITLE
It can working web, desktop?

### ISSUE THREAD

**Issue by jpoh281** [abobija/esp-smartconfig-dart#1]
It can working web, desktop?

**Comment by abobija** [comment]
@jpoh281 yes it can work on any platform (including desktop),
 except runtime js (web), because browsers does not supports plain UDP protocol.

If you are going to test on desktop make sure that UDP port 18266 is open for incoming data

**Comment by jpoh281** [comment]
OMG...
I made this plugin https://pub.dev/packages/esptouch_smartconfig 
but yours is more awesome than mine! !
Good.

**Comment by abobija** [comment]
Thank you.
If you found any bugs, issues or have request for library improvements, feel free to write me.

Best regards
