### ISSUE TITLE
provisioner.listen can not get any data

### ISSUE THREAD

**Issue by TONYCHOU81905** [abobija/esp-smartconfig-dart#18]
Hello everyone,
below is my code, my esp can receive wifi information , but my app can not receive any data that esp is connected.
Does there anyone face the same issue as me?

provisioner.listen((response) {
            debugPrint('SSID:${response.ipAddressText}');
            debugPrint("\n"
                "\n------------------------------------------------------------------------\n"
                "Device ($response) is connected to WiFi!"
                "\n------------------------------------------------------------------------\n");
          });

**Comment by abobija** [comment]
From README:

> If you are going to use this library on Desktop platforms make sure that UDP port 18266 is open in the firewall for incoming data.

**Comment by TONYCHOU81905** [comment]
but I'm using on phone, but neither ios nor Android can not listen to any data.
Is there any configuration that I need to be careful?
Thank you

**Comment by abobija** [comment]
For Android make sure to have these permissions in the AndroidManifest.xml file:

```xml
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.CHANGE_WIFI_MULTICAST_STATE" />
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

**Comment by TONYCHOU81905** [comment]
But in ios, we face the same issue.
And we have already added Multicast capability in my project

**Comment by yenyichau** [comment]
Any idea? Added Multicast still not working.
