### ISSUE TITLE
reservedDataLengthMax = 127;

### ISSUE THREAD

**Issue by kristsm** [abobija/esp-smartconfig-dart#32]
Is there a reason for limiting reserved data lenght to 127 bytes? Maybe the reason is behind esp32 side of esptouch V2?  My app would need to send about twice amount of data, otherwise I need to run webserver on esp32 afterwards to provide additional provision data ( which I really do not want to). 
Thanks!

**Comment by abobija** [comment]
Yes, per ESPTOUCH_V2 protocol (at esp32 side), the max data length is 127 bytes.

**Comment by kristsm** [comment]
Thanks! Is it like a software limitation which could be changed somewhere or hardware limitations?

**Comment by abobija** [comment]
I think the ESP-IDF framework limits it.
