### ISSUE TITLE
ssid length error 

### ISSUE THREAD

**Issue by app-vrb** [abobija/esp-smartconfig-dart#4]
Hi I found a problem on the plugin.
In case the SSID length is less than 9 characters it trow this error:
[VERBOSE-2:dart_isolate.cc(1111)] Unhandled exception:
RangeError: Invalid value: Not in inclusive range 0..72: 75
#0      List.insertAll (dart:core-patch/growable_array.dart:44:7)
#1      EspTouch._dataCodes.<anonymous closure> (package:esp_smartconfig/src/protocols/esptouch.dart:62:17)
#2      _IntListMixin.forEach (dart:typed_data-patch/typed_data_patch.dart:215:8)
#3      EspTouch._dataCodes (package:esp_smartconfig/src/protocols/esptouch.dart:60:19)
#4      EspTouch.prepare (package:esp_smartconfig/src/protocols/esptouch.dart:27:19)
#5      Provisioner._startProvisioning (package:esp_smartconfig/src/provisioner.dart:201:9)
<asynchronous suspension>

**Comment by abobija** [comment]
I will investigate this as soon as I found some free time. Thanks for feedback.

**Comment by app-vrb** [comment]
Thanks a lot for the answer.Il 15 mar 2022 18:34, Alija Bobija ***@***.***> ha scritto:
I will investigate this as soon as I found some free time. Thanks for feedback.

**Comment by abobija** [comment]
This issue is same as issue #6, let's close this and continue further discussion there.
